version: "3"
services:
  client:
    build:
      dockerfile: Containerfile
    ports:
      - 5000:5000
    environment:
      PYTHONUNBUFFERED: 1
  server:
    build:
      context: server
      dockerfile: Containerfile
    environment:
      PYTHONUNBUFFERED: 1
    deploy:
      replicas: 2 
    profiles: 
      - server